let productos =[
    {id:"1",nombre:"taza roja",categoria:"tazas", stock:"5", precio:"200", foto:"https://www.promo-todo.com/p_i/Disenio/grandes/dtaz-01-r.jpg",descripcion:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
    {id:"2",nombre:"taza verde",categoria:"tazas", stock:"8", precio:"500", foto:"https://http2.mlstatic.com/D_NQ_NP_665130-MLA51903369756_102022-W.jpg",descripcion:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
    {id:"3",nombre:"plato rojo",categoria:"platos", stock:"9", precio:"200", foto:"https://thumbs.dreamstime.com/b/plato-rojo-vac%C3%ADo-en-el-fondo-blanco-119547985.jpg",descripcion:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
    {id:"4",nombre:"cubierto negro",categoria:"cubiertos", stock:"2", precio:"200", foto:"https://d3ugyf2ht6aenh.cloudfront.net/stores/960/261/products/img_20771-28bc8369919d9da0b215950099327321-1024-1024.jpg",descripcion:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
    {id:"5",nombre:"recipiente redondo",categoria:"recipientes", stock:"4", precio:"200", foto:"https://assets.tramontina.com.br/upload/tramon/imagens/FAR/61224281PNM001G.png",descripcion:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."},
  ];
export const task = (id)=>{ return new Promise((positivo,negativo)=>{
positivo( id ? productos.filter(prod=>prod.id===id) : productos );

negativo("error"); 
}) }
